### ISSUE TITLE
[PE-D] edit success message

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-TIC4002-F18-2/tp2#51]
![image.png](https://raw.githubusercontent.com/badfr0g/ped/main/files/67720917-79dc-4664-93bf-87bd2ec90e5f.png)
Edited Person did not refresh after edit

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: badfr0g/ped#2

**Comment by zyjarvis** [comment]
Edited person is to show the person data before editing. It should be correct here.
